apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: virt-density-{{.Iteration}}
  labels:
    kubevirt.io/os: cirros
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/os: cirros
    spec:
      terminationGracePeriodSeconds: 0
      domain:
        resources:
          requests:
            memory: 32Mi
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - disk:
              bus: virtio
            name: cloudinitdisk
          - name: emptydisk
            disk:
              bus: virtio
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/rsevilla/cirros:0.6.3
          imagePullPolicy: IfNotPresent
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: perfscale
            chpasswd: { expire: False }
      - name: emptydisk
        emptyDisk:
          capacity: "10Mi"
