apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: cluster-queue-{{ sub .Replica 1 }}
spec:
  namespaceSelector: {} # match all.
  cohortName: "shared-cq"
  resourceGroups:
  - coveredResources: [pods]
    flavors:
    - name: "default"
      resources:
      - name: "pods"
        nominalQuota: {{ .PODS_QUOTA }}