---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  deletionStrategy: {{.DELETION_STRATEGY}}
  measurements:
    - name: vmiLatency
      thresholds:
        - conditionType: VMIRunning
          metric: P99
          threshold: {{.VMI_RUNNING_THRESHOLD}}
metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      esServers: ["{{.ES_SERVER}}"]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: opensearch
{{ end }}
{{ if .LOCAL_INDEXING }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}
jobs:
  {{ if .ENABLE_LAYER_3 }}
  - name: create-udn-l3
  {{ else }}
  - name: create-udn-l2
  {{ end }}
    namespace: virt-density-udn
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 15s
    churnConfig:
      cycles: {{.CHURN_CYCLES}}
      duration: {{.CHURN_DURATION}}
      percent: {{.CHURN_PERCENT}}
      delay: {{.CHURN_DELAY}}
      mode: {{.CHURN_MODE}}
    jobPause: {{.JOB_PAUSE}}
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
      k8s.ovn.org/primary-user-defined-network: ""
    objects:
      {{ if .ENABLE_LAYER_3 }}
      - objectTemplate: udn_l3.yml
        replicas: 1
      {{ else }}
      - objectTemplate: udn_l2.yml
        replicas: 1
      {{ end }}

  - name: virt-density-udn
    namespace: virt-density-udn
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    preLoadImages: false
    preLoadPeriod: 15s
    waitWhenFinished: true
    jobPause: 2m
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
      k8s.ovn.org/primary-user-defined-network: ""
    objects:

      - objectTemplate: vm-client.yml
        replicas: {{.VMS_PER_ITERATION}}
        inputVars:
          bindingMethod: {{.UDN_BINDING_METHOD}}
          vmImage: {{.VM_IMAGE}}
      - objectTemplate: vm-server.yml
        replicas: 1
        inputVars:
          bindingMethod: {{.UDN_BINDING_METHOD}}
          vmImage: {{.VM_IMAGE}}
