apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: virt-client-{{.Iteration}}-{{.Replica}}
  labels:
    kubevirt.io/os: fedora
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/os: fedora
    spec:
      terminationGracePeriodSeconds: 0
      domain:
        resources:
          requests:
            memory: 256Mi
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - disk:
              bus: virtio
            name: cloudinitdisk
          - name: emptydisk
            disk:
              bus: virtio
          interfaces:
          - name: primary-udn-net
            binding:
              name: {{.bindingMethod}}
      networks:
      - name: primary-udn-net
        pod: {}
      volumes:
      - name: containerdisk
        containerDisk:
          image: {{.vmImage}}
          imagePullPolicy: IfNotPresent
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: perfscale
            chpasswd: { expire: False }
            runcmd:
              - dnf install -y --nodocs curl
              - curl -sS --fail 10.132.0.5 --retry 30 --retry-delay 10
      - name: emptydisk
        emptyDisk:
          capacity: "50Mi"
