---
global:
  gc: {{.GC}}
  measurements:
    - name: podLatency
metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      esServers: ["{{.ES_SERVER}}"]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: opensearch
{{ end }}
{{ if .LOCAL_INDEXING }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}

jobs:
  - name: add-default-storage
    namespace: pvc-density
    jobIterations: 1
    namespacedIterations: false
    podWait: false
    waitWhenFinished: true
    skipIndexing: true
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:

  - name: pvc-density
    namespace: pvc-density
    jobIterations: {{.JOB_ITERATIONS}}
    cleanup: true
    namespacedIterations: false
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 10s
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:

      - objectTemplate: pvc.yml
        replicas: 1
        inputVars:
          claimSize: {{.CLAIM_SIZE}}
          storageClassName: {{.STORAGE_CLASS_NAME}}

      - objectTemplate: pod.yml
        replicas: 1
        inputVars:
          containerImage: registry.k8s.io/pause:3.1
