# This workload has special hardware requirements.
# In order to meet those requirements we have added CI tests in e2e-benchmarking: 
# https://github.com/openshift/release/tree/master/ci-operator/step-registry/cloud-bulldozer/e2e-benchmarking
---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  deletionStrategy: {{.DELETION_STRATEGY}}
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: {{.POD_READY_THRESHOLD}}
{{ if .SVC_LATENCY }}
    - name: serviceLatency
      svcTimeout: 1m
{{ end }}
metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      esServers: ["{{.ES_SERVER}}"]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: opensearch
{{ end }}
{{ if .LOCAL_INDEXING }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}

jobs:
  - name: bgp-setup
    namespace: metallb-system
    jobIterations: 1
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: false
    objects:
      - objectTemplate: ipaddresspool.yml
        replicas: 1

      - objectTemplate: bgpadvertisement.yml
        replicas: 1

      - objectTemplate: bgppeer.yml
        replicas: 1

  - name: rds
    namespace: rds
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 15s
    churn: {{.CHURN}}
    churnCycles: {{.CHURN_CYCLES}}
    churnDuration: {{.CHURN_DURATION}}
    churnPercent: {{.CHURN_PERCENT}}
    churnDelay: {{.CHURN_DELAY}}
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects:

      - objectTemplate: secret.yml
        replicas: 42

      - objectTemplate: configmap.yml
        replicas: 30

      - objectTemplate: np-deny-all.yml
        replicas: 1

      - objectTemplate: np-allow-from-clients.yml
        replicas: 1

      - objectTemplate: np-allow-from-ingress.yml
        replicas: 1

      - objectTemplate: sriov-network.yml
        replicas: 1

      - objectTemplate: sriov-dpdk-network.yml
        replicas: 2

      - objectTemplate: service.yml
        replicas: 20

      - objectTemplate: service-lb.yml
        replicas: 1

      - objectTemplate: route.yml
        replicas: 2

      - objectTemplate: deployment-server.yml
        replicas: 15
        inputVars:
          podReplicas: 2

      - objectTemplate: deployment-client.yml
        replicas: 10
        inputVars:
          podReplicas: 2
          ingressDomain: {{.INGRESS_DOMAIN}}

      - objectTemplate: deployment-dpdk.yml
        replicas: 2
        inputVars:
          podReplicas: 1
          dpdk_cores: {{.DPDK_CORES}}
          dpdk_hugepages: {{.DPDK_HUGEPAGES}}
          perf_profile: {{.PERF_PROFILE}}

