---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  measurements:
    - name: podLatency
metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      esServers: ["{{.ES_SERVER}}"]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: {{.INDEXING_TYPE}}
{{ end }}
{{ if .LOCAL_INDEXING }}
  - metrics: [{{.TS_METRICS}}]
    indexer:
      type: local
      metricsDirectory: reporting-metrics
  - metrics: [metrics-report.yml]
    indexer:
      type: local
      metricsDirectory: reporting-metrics
{{ end }}
jobs:
  - name: create-bindings
    namespace: networkpolicy-multitenant
    skipIndexing: true
    jobIterations: 1
    objects:
      - objectTemplate: ../clusterrole.yml
        replicas: 1
      - objectTemplate: ../clusterrolebinding.yml
        replicas: 1

  - name: networkpolicy-multitenant
    namespace: networkpolicy-multitenant
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 15s
    churn: {{.CHURN}}
    churnCycles: {{.CHURN_CYCLES}}
    churnDuration: {{.CHURN_DURATION}}
    churnPercent: {{.CHURN_PERCENT}}
    churnDelay: {{.CHURN_DELAY}}
    churnDeletionStrategy: {{.CHURN_DELETION_STRATEGY}}
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    
    objects:
      - objectTemplate: deny-all.yml
        replicas: 1

      - objectTemplate: multitenant-networkpolicy.yml
        replicas: 3
        inputVars:
          job_iterations: {{.JOB_ITERATIONS}}
      
      - objectTemplate: scraper.yml
        replicas: 20
        inputVars:
          label1: "unused"
          label2: "unused"
          workload: "networkpolicy-multitenant"
          es_server: "{{.ES_SERVER}}"
          es_index: "networkpolicy-enforcement"
          set: "1"
