name: Execute tests on OCP
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      OPENSHIFT_SERVER:
        required: true
      OPENSHIFT_USER:
        required: true
      OPENSHIFT_PASSWORD:
        required: true
jobs:
  ocp-e2e-ci:
    runs-on: ubuntu-latest
    concurrency:
      group: ocp-e2e-ci
    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false

    - name: Download kube-burner-ocp binary
      uses: actions/download-artifact@v4
      with:
        name: kube-burner-ocp
        path: /tmp/

    - name: Install bats
      uses: bats-core/bats-action@1.5.4
      with:
        bats-version: 1.10.0
        support-install: false
        assert-install: false
        detik-install: false
        file-install: false

    - name: Install oc
      uses: redhat-actions/oc-installer@v1

    - name: Authenticate against OCP cluster
      run: oc login -u ${OPENSHIFT_USER} -p ${OPENSHIFT_PASSWORD} ${OPENSHIFT_SERVER} --insecure-skip-tls-verify=true
      env:
        OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
        OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
        OPENSHIFT_PASSWORD: ${{ secrets.OPENSHIFT_PASSWORD }}

    - name: Install Virtctl
      run: |
        export VERSION=$(curl https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt)
        wget https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/virtctl-${VERSION}-linux-amd64 -O /tmp/virtctl
        chmod +x /tmp/virtctl

    - name: Execute Tests
      run: |
        export PATH=${PATH}:/tmp/
        chmod +x /tmp/kube-burner-ocp
        make test-ocp
      env:
        TERM: linux
        OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
        OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
        OPENSHIFT_PASSWORD: ${{ secrets.OPENSHIFT_PASSWORD }}
        PERFSCALE_PROD_ES_SERVER: ${{ secrets.PERFSCALE_PROD_ES_SERVER }}
